import type { PublicInstitution, PublicLab } from '../types';

export const publishedLab: PublicLab = {
  lab_id: 'imperial-adaptive-systems',
  lab_name: 'Adaptive Systems Lab',
  department: 'Computing',
  campus_ids: ['imperial-south-kensington', 'imperial-white-city'],
  campus_evidence: [
    {
      campus_id: 'imperial-south-kensington',
      campus_label: 'South Kensington',
      source_item_count: 5,
      unique_author_count: 3,
      date_range_start: '2025-09-03',
      date_range_end: '2025-10-01',
    },
    {
      campus_id: 'imperial-white-city',
      campus_label: 'White City',
      source_item_count: 3,
      unique_author_count: 2,
      date_range_start: '2025-09-15',
      date_range_end: '2025-10-11',
    },
    {
      campus_id: null,
      campus_label: 'Location unspecified',
      source_item_count: 1,
      unique_author_count: 1,
      date_range_start: '2025-09-20',
      date_range_end: '2025-09-20',
    },
  ],
  campus_summaries: [],
  research_areas: ['Machine Learning', 'Robotics'],
  has_summary: true,
  message: null,
  confidence: 'medium',
  provenance: {
    source_item_count: 9,
    unique_author_count: 5,
    withheld_item_count: 2,
    date_range_start: '2025-09-03',
    date_range_end: '2025-10-11',
    generated_at: '2026-07-23',
    model: 'offline-heuristic',
  },
  summary: {
    overview: 'Across 9 anonymised items from 5 authors, perceptions cluster into a few themes.',
    positive_themes: [
      {
        theme: 'Supportive supervision',
        description: 'Several items describe supervisors as approachable.',
        supporting_item_count: 4,
      },
    ],
    challenge_themes: [
      {
        theme: 'Workload and hours',
        description: 'Some items report long hours.',
        supporting_item_count: 3,
      },
    ],
    neutral_observations: ['The group is international.'],
    confidence: 'medium',
    limitations: ['Statements are self-selected and unverified.'],
    withheld_item_count: 2,
  },
};

export const insufficientLab: PublicLab = {
  lab_id: 'imperial-neurotech',
  lab_name: 'Neurotechnology Lab',
  department: 'Bioengineering',
  campus_ids: ['imperial-south-kensington'],
  campus_evidence: [],
  campus_summaries: [],
  research_areas: ['Neurotechnology'],
  has_summary: false,
  message: 'Insufficient public data for a reliable summary.',
  confidence: null,
  provenance: null,
  summary: null,
};

export const institution: PublicInstitution = {
  institution_id: 'imperial',
  name: 'Imperial College London',
  short_name: 'Imperial',
  region: 'london',
  map_center: { latitude: 51.4988, longitude: -0.1749 },
  website: 'https://www.imperial.ac.uk',
  campuses: [
    {
      campus_id: 'imperial-south-kensington',
      name: 'South Kensington Campus',
      short_name: 'South Kensington',
      latitude: 51.4988,
      longitude: -0.1749,
      address: 'Exhibition Road, London SW7 2AZ',
      location_type: 'university_campus',
      represented_lab_count: 1,
      source_item_count: 5,
      unique_author_count: 3,
      evidence_status: 'summary_available',
      confidence: 'low',
      provenance: publishedLab.provenance,
      summary: publishedLab.summary,
    },
    {
      campus_id: 'imperial-white-city',
      name: 'White City Campus',
      short_name: 'White City',
      latitude: 51.5151,
      longitude: -0.2243,
      address: 'Wood Lane, London W12 0BZ',
      location_type: 'university_campus',
      represented_lab_count: 1,
      source_item_count: 3,
      unique_author_count: 2,
      evidence_status: 'below_threshold',
      confidence: null,
      provenance: {
        ...publishedLab.provenance!,
        source_item_count: 3,
        unique_author_count: 2,
      },
      summary: null,
    },
  ],
  campus_unspecified: {
    campus_id: null,
    campus_label: 'Location unspecified',
    source_item_count: 1,
    unique_author_count: 1,
    date_range_start: '2025-09-20',
    date_range_end: '2025-09-20',
  },
  represented_lab_count: 1,
  source_item_count: 9,
  unique_author_count: 5,
  date_range_start: '2025-09-03',
  date_range_end: '2025-10-11',
  overall_themes: ['Supportive supervision', 'Workload and hours'],
  confidence: 'medium',
  last_updated: '2026-07-23',
  departments: ['Computing', 'Bioengineering'],
  research_areas: ['Machine Learning', 'Robotics', 'Neurotechnology'],
  labs: [publishedLab, insufficientLab],
};
